version: '3'
services:

  # Serviço MySQL
  mysql-db:
    build:
      context: ./app_mysql
      dockerfile: dockerfile_sql
    ports:
      - "3306:3306"

  # Serviço MySQL
  java-app:
    build:
      context: ./app_java
      dockerfile: dockerfile_java
    ports:
      - "8080:8080"