version: '3'
services:

  # Serviço MySQL
  mysql-db:
    build:
    container_name: safe_monitor
    restart: always
    environment:
    volumes:
    - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"

      context: ./app_mysql
      dockerfile: dockerfile_sql

