# Use a imagem oficial do SQL Server
FROM mcr.microsoft.com/mssql/server:2019-latest

# Configuração das variáveis de ambiente
ENV SA_PASSWORD=SafeMonitor23@
ENV ACCEPT_EULA=Y

# Criar um diretório para scripts SQL personalizados
WORKDIR /usr/src/app
COPY ./initialize.sql /usr/src/app

# Copiar scripts SQL para o diretório de inicialização
COPY ./initialize.sql /docker-entrypoint-initdb.d/

# Abra a porta padrão do SQL Server
EXPOSE 1433

# Comando de entrada para iniciar o SQL Server
CMD ["/opt/mssql/bin/sqlservr"]