# Use a imagem oficial do MySQL
FROM mysql:latest

# Configurar variáveis de ambiente
ENV MYSQL_ROOT_PASSWORD=urubu100
ENV MYSQL_DATABASE=safe_monitor

# Expor a porta padrão do SQL Server (1433)
EXPOSE 3306

# Copiar scripts de inicialização (opcional)
COPY ./scripts/ /docker-entrypoint-initdb.d/