# Use a imagem oficial do Node.js
FROM node:14

# Criar diretório de aplicação
WORKDIR /usr/src/app

# Copiar dependências do projeto
COPY ./SafeMonitor-Frontend ./package*.json ./

# Instalar dependências
RUN npm install

# Copiar código fonte
COPY ./SafeMonitor-Frontend ./

# Expor a porta 3000 (ou a porta que sua aplicação Node.js está usando)
EXPOSE 80

# Comando para iniciar a aplicação
CMD ["npm", "start"]